# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 23:30
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('contact_address1', models.CharField(max_length=50)),
                ('contact_address2', models.CharField(blank=True, max_length=50)),
                ('contact_city', models.CharField(max_length=50)),
                ('contact_state', models.CharField(max_length=20)),
                ('contact_zip', models.CharField(max_length=10)),
                ('crop_address1', models.CharField(blank=True, max_length=50)),
                ('crop_address2', models.CharField(blank=True, max_length=50)),
                ('crop_city', models.CharField(blank=True, max_length=50)),
                ('crop_state', models.CharField(blank=True, max_length=20)),
                ('crop_zip', models.CharField(blank=True, max_length=10)),
                ('crop_type', models.CharField(choices=[('b', 'Backyard Grower'), ('f', 'Commercial Farmer')], max_length=1)),
                ('receipt_preference', models.CharField(choices=[('e', 'Email'), ('m', 'Mail')], max_length=1)),
                ('crop_description', models.TextField()),
                ('equipment_needed', models.TextField()),
                ('load_in', models.TextField()),
                ('bathroom_available', models.BooleanField(default=False)),
                ('power_lines', models.TextField()),
                ('pets', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
